### ISSUE TITLE
Wikipedia articles level 4

### ISSUE THREAD

**Issue by JasperHG90** [amirouche/sensimark#5]
Hey Amirouche,

Thanks for this project. We used this as the basis for a project at our university, and wanted to share it with you. Maybe it's useful for you.

We download the level 4 vital articles list (instead of level 3). The scrapy project can be found [here](https://github.com/JasperHG90/WikiVitalArticles).

We also use several [neural network architectures](https://github.com/JasperHG90/PatternRecognition) to classify the articles into their respective categories (only main categories at the moment). Instead of Word2Vec we use pre-trained FastText embeddings.

Best,

Jasper.

**Comment by amirouche** [comment]
Thanks a lot for the feedback! 

Very interesting! 

I tried fasttext (in a hurry) it was giving me very poor results.  

I understand you found your way through the code!  Congrats because I do not think the code is very neat or easy to navigate.  I will look at your code. 

https://github.com/JasperHG90/PatternRecognition is private apparently.

**Comment by amirouche** [comment]
@JasperHG90 Or you had in mind something I could do? I mean what do you expect?

**Comment by JasperHG90** [comment]
Public now. Nothing that you can do. Just FYI in case you were still working on this.

**Comment by amirouche** [comment]
Interesting read.  Thanks for sharing.
